### ISSUE TITLE
如果clone到iCloud云盘中的话，无法正常执行。请问有没有好的办法进行同步呢。

### ISSUE THREAD

**Issue by hstdt** [Jeff2Ma/launchd-with-networkchange#2]
![image](https://user-images.githubusercontent.com/10215098/41834043-53db4c10-7885-11e8-9f79-a1adcca1f86f.png)

![image](https://user-images.githubusercontent.com/10215098/41834108-8d841a3c-7885-11e8-9d3d-bb51142d8c6a.png)

**Comment by Jeff2Ma** [comment]
应该自己重新建立下软链就可以了。
